--#1
CREATE TABLE customers(
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	email VARCHAR(30) UNIQUE
);
CREATE TABLE orders(
	id SERIAL PRIMARY KEY,
	customerId INTEGER,
	sum NUMERIC(10,4),
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (customerId) INTEGER REFERENCES customers (id)
);